const data={
"Kimia":[["Kimia Dasar",["Struktur Atom & Teori Model Atom","Sistem & Sifat Periodik Unsur","Ikatan Kimia, Geometri Molekul & Interaksi Antarmolekul","Hukum Dasar Kimia, Stoikiometri & Persamaan Reaksi"]],["Kimia Analitik",["Larutan & Kesetimbangan Larutan","Asam-Basa & Pengukuran pH","Sistem Koloid"]],["Kimia Fisik",["Energetika Reaksi / Termokimia","Dinamika Reaksi / Laju Reaksi & Kesetimbangan"]],["Kimia Organik",["Struktur & Kereaktifan Senyawa Karbon / Hidrokarbon"]]],
"Matematika Dasar":[["Bilangan Real",["Jenis & sifat bilangan","Operasi dasar","Eksponen bulat","Eksponen pecahan"]],["Aljabar",["Sistem persamaan linear multivariabel","Sistem pertidaksamaan linear multivariabel","Program linear","Fungsi linear","Fungsi kuadrat","Fungsi rasional","Fungsi invers","Fungsi komposisi"]],["Barisan & Deret",["Aritmetika","Geometri","Bunga","Pertumbuhan","Peluruhan"]],["Geometri & Pengukuran",["Garis, sudut & bidang","Kesebangunan","Kongruensi","Pythagoras","Translasi","Refleksi","Rotasi","Dilatasi","Keliling","Luas","Volume"]],["Trigonometri",["sin","cos","tan","csc","sec","cot"]],["Data & Peluang",["Tabel","Grafik","Diagram","Mean, median, modus","Ukuran penyebaran","Peluang"]]],
"Matematika Lanjut":[["Aljabar",["Matriks","Determinan 2×2","Determinan 3×3","Invers matriks","Operasi matriks","Polinomial","Pemfaktoran","Suku sisa","Polinomial orde ≤4"]],["Fungsi Lanjut",["Polinom","Rasional","Akar","Eksponen","Logaritma","Nilai mutlak","Trigonometri"]],["Geometri & Pengukuran",["Vektor bidang","Vektor ruang","Panjang vektor","Operasi vektor","Lingkaran","Persamaan lingkaran","Garis singgung","Luas & keliling lingkaran","Transformasi dengan matriks"]],["Trigonometri & Kalkulus",["Limit fungsi aljabar","Limit fungsi trigonometri","Limit tanpa L'Hôpital"]]],
"Bahasa Indonesia":[["Pemahaman Tekstual",["Kata serapan","Latar","Karakter","Kosakata","Bagan teks","Kerangka teks"]],["Pemahaman Inferensial",["Ide pokok","Gagasan pendukung","Hubungan antarkalimat","Hubungan antarparagraf","Prediksi kelanjutan cerita"]],["Evaluasi & Apresiasi",["Relevansi teks","Keakuratan data","Keakuratan bahasa","Evaluasi karakter","Puisi","Prosa","Drama","Respons emosional"]]],
"Bahasa Inggris":[["Textual Understanding",["Explicit information","Classifying","Outlining","Summarizing","Synthesizing sources"]],["Inferential Understanding",["Main idea","Topic","Purpose","Moral value","Cause & effect","Sequence of events","Character traits","Predicting outcomes"]],["Evaluation & Appreciation",["Reality vs fantasy","Fact vs opinion","Validity","Accuracy","Emotional response","Personal response"]]]
};
let state=JSON.parse(localStorage.tkaMaster||'{"done":[],"target":750,"study":0,"streak":7,"score":682,"theme":"light"}');
const key=x=>btoa(unescape(encodeURIComponent(x))).replaceAll('=','');
const all=()=>Object.values(data).flat().flatMap(x=>x[1]).length;
const doneCount=()=>state.done.length;
function save(){localStorage.tkaMaster=JSON.stringify(state)}
function go(page){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({home:home,materi:materi,jadwal:jadwal,stats:stats,target:target}[page]||home)()}
function home(){content.innerHTML=`<section class="hero"><div class="hero-row"><div><div class="muted" style="color:#ffffffb8">TARGET TKA</div><div class="score">${state.score}</div><div>Target ${state.target} · +34 minggu ini</div></div><div class="ring"><div>${Math.round(doneCount()/all()*100)}%</div></div></div><div style="margin:18px 0 6px;display:flex;justify-content:space-between"><span>Progress materi</span><b>${doneCount()}/${all()}</b></div><div class="progress"><i style="width:${doneCount()/all()*100}%"></i></div></section>
<div class="section-title"><h2>Ringkasan</h2></div><div class="grid"><div class="card metric">🔥 <b>${state.streak}</b><div class="muted">hari streak</div></div><div class="card metric">⏱️ <b>${state.study}j</b><div class="muted">belajar</div></div></div>
<div class="section-title"><h2>Belajar Hari Ini</h2><span class="tag">3 sesi</span></div>
${[['🧪','Kimia','Asam-Basa & Pengukuran pH','45 menit'],['📐','Matematika','Fungsi Kuadrat','30 menit'],['🇬🇧','English','Main Idea & Topic','30 menit']].map(x=>`<div class="card" style="margin-bottom:10px"><div style="font-size:11px;font-weight:800;color:#777b91">${x[0]} ${x[1]}</div><b>${x[2]}</b><div class="muted">${x[3]}</div><button class="btn secondary" style="margin-top:10px" onclick="quiz('${x[2]}')">Mulai Belajar →</button></div>`).join('')}`; }
function materi(){content.innerHTML=`<div class="section-title"><h2>Checklist Materi</h2><span class="badge">${doneCount()} / ${all()}</span></div>${Object.entries(data).map(([sub,groups])=>`<div class="subject"><div class="subject-head"><div><b>${sub}</b><div class="muted">${groups.reduce((a,g)=>a+g[1].length,0)} materi</div></div><span>›</span></div><div class="subject-body">${groups.map(g=>`<div class="group"><div class="group-title">${g[0]}</div>${g[1].map(m=>`<label class="check"><input type="checkbox" ${state.done.includes(m)?'checked':''} onchange="toggleDone(this,'${esc(m)}')"><span>${m}</span></label>`).join('')}</div>`).join('')}</div></div>`).join('')}`}
function jadwal(){content.innerHTML=`<div class="section-title"><h2>Jadwal Belajar</h2><button class="btn" onclick="addSession()">+ Sesi</button></div><div class="card" style="margin-bottom:15px"><b>Sabtu, 29 Agustus</b><div class="muted">Target hari ini: 1 jam 45 menit</div></div>${[['16:00','Kimia','Asam-Basa'],['17:00','Matematika','Fungsi Kuadrat'],['19:30','English','Main Idea & Topic'],['20:15','Mixed Quiz','20 Questions']].map((x,i)=>`<div class="schedule"><div class="time">${x[0]}</div><div class="dot"></div><div style="flex:1"><b>${x[1]}</b><div class="muted">${x[2]}</div></div><span>${i===0?'✓':'○'}</span></div>`).join('')}`;}
function stats(){let p=Math.round(doneCount()/all()*100);content.innerHTML=`<div class="section-title"><h2>Statistik Belajar</h2></div><div class="hero"><div class="muted" style="color:#ffffffb8">SKOR SIMULASI</div><div class="score">${state.score}</div><div>↑ +34 dari simulasi sebelumnya</div></div><div class="section-title"><h2>Akurasi per bidang</h2></div>${[['Matematika',76],['Kimia',68],['Bahasa Indonesia',82],['Bahasa Inggris',74]].map(x=>`<div class="card" style="margin-bottom:10px"><div class="kpi"><b>${x[0]}</b><b>${x[1]}%</b></div><div class="bar"><i style="width:${x[1]}%"></i></div></div>`).join('')}<div class="section-title"><h2>Analisis</h2></div><div class="grid"><div class="card"><span class="tag">TERKUAT</span><p>Ide Pokok</p><b>91%</b></div><div class="card"><span class="tag">PERLU LATIHAN</span><p>Stoikiometri</p><b>51%</b></div></div>`}
function target(){content.innerHTML=`<div class="section-title"><h2>Target TKA</h2></div><div class="card"><div class="muted">TARGET SKOR</div><div class="score" style="color:#6d5dfc">${state.target}</div><div class="muted">Skor saat ini ${state.score}</div><div class="bar" style="margin:15px 0"><i style="width:${Math.min(100,state.score/state.target*100)}%"></i></div><button class="btn" onclick="setTarget()">Ubah Target</button></div><div class="section-title"><h2>Target Mingguan</h2></div><div class="grid">${[['🎯','12','materi selesai'],['📝','150','soal'],['⏱️','7 jam','belajar'],['🔥','7','hari streak']].map(x=>`<div class="card metric">${x[0]} <b>${x[1]}</b><div class="muted">${x[2]}</div></div>`).join('')}</div><div class="section-title"><h2>Achievement</h2></div><div class="card">🏅 First Step &nbsp; 🔥 7 Day Streak &nbsp; 🎯 Target 750</div>`}
function toggleDone(el,m){if(el.checked&&!state.done.includes(m))state.done.push(m);else state.done=state.done.filter(x=>x!==m);save();materi()}
function setTarget(){let n=prompt('Target skor TKA:',state.target);if(n&&+n>0){state.target=+n;save();target()}}
function addSession(){let x=prompt('Nama sesi belajar:');if(x){alert('Sesi “'+x+'” ditambahkan.');}}
function quiz(topic){let modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-box"><div class="section-title"><h2>Latihan · ${topic}</h2><button class="icon-btn" onclick="this.closest('.modal').remove()">×</button></div><div class="q">Jika kamu sudah mempelajari materi ini, langkah terbaik untuk menguji penguasaan adalah…</div><button class="option" onclick="answer(this,false)">A. Membaca ulang tanpa latihan</button><button class="option" onclick="answer(this,true)">B. Mengerjakan soal lalu meninjau pembahasan</button><button class="option" onclick="answer(this,false)">C. Menghafalkan semua halaman</button><div id="feedback" class="muted" style="margin-top:12px"></div></div>`;document.body.appendChild(modal)}
function answer(el,ok){document.querySelectorAll('.option').forEach(x=>x.disabled=true);el.classList.add(ok?'correct':'');document.getElementById('feedback').innerHTML=ok?'✓ Benar! Review pembahasan setelah latihan membantu menemukan kelemahan.':'Belum tepat. Coba pilih strategi belajar yang melibatkan latihan dan evaluasi.'}
function esc(s){return s.replaceAll("'","\\'")}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',state.theme==='dark');save()}
document.body.classList.toggle('dark',state.theme==='dark');go('home');